name: Run tests in container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: docker build -t app .
    - name: Run pytest
      run: >
        docker run -it app bash
        pytest app.py
